import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { listMemories, searchMemories } from "./store.js";
import { currentProject } from "./project.js";
import { recallHome } from "./paths.js";

// generate ~/.recall/context-<safe-project>.md for @-import into claude.md / agents.md.
export async function writeContext(opts: { project?: string; limit?: number; seed?: string } = {}): Promise<string> {
  const project = opts.project ?? currentProject();
  const limit = opts.limit ?? 12;
  const memories = opts.seed
    ? await searchMemories(opts.seed, limit, project)
    : listMemories(limit, project);

  const safe = project.replace(/[^a-z0-9._-]+/gi, "-").replace(/-+/g, "-").toLowerCase();
  const path = join(recallHome(), `context-${safe}.md`);
  const body = memories.length
    ? memories.map((m) => `- (#${m.id}, ${m.created_at.slice(0, 10)}) ${m.content.replace(/\s+/g, " ").trim().slice(0, 240)}`).join("\n")
    : "_no memories yet for this project. they'll appear here as you work._";

  writeFileSync(path,
    `# recall context for ${project}\n` +
    `<!-- generated by \`recall context\` on ${new Date().toISOString()} -->\n\n` +
    `${body}\n`);
  return path;
}
